# Generated by Django 5.0.3 on 2024-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_stay_buyer_remove_stay_listing_delete_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenitie', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
