# Generated by Django 5.0.3 on 2024-04-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_amenitie_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitie',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='amenities', to='listings.listing'),
        ),
    ]
