# Generated by Django 5.0.3 on 2024-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_amenitie_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='attributes',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='amenitie',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='listings.listing'),
        ),
    ]
