# Generated by Django 5.0.3 on 2024-04-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_attributes_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(default='house', max_length=4),
            preserve_default=False,
        ),
    ]
