# Generated by Django 5.0.3 on 2024-05-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='listing',
        ),
    ]
