# Generated by Django 5.0.3 on 2024-10-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='quantity',
        ),
    ]
