# Generated by Django 5.0.3 on 2024-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0002_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
