# Generated by Django 5.0.3 on 2024-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='guests',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='stay',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stay',
            name='infants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stay',
            name='pets',
            field=models.IntegerField(default=0),
        ),
    ]
