# Generated by Django 5.0.3 on 2024-04-24 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0003_rename_guests_stay_adults_stay_children_stay_infants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_requests', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='capstoneapp.listing')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='capstoneapp.stay')),
            ],
        ),
    ]
