# Generated by Django 5.0.3 on 2024-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0004_user_profile_pic_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/'),
        ),
    ]
