# Generated by Django 5.0.3 on 2024-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0005_user_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Dominican Republic', max_length=255),
            preserve_default=False,
        ),
    ]
