# Generated by Django 5.0.3 on 2024-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0005_request_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accepted',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
