# Generated by Django 5.0.3 on 2024-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
