# Generated by Django 5.0.3 on 2024-04-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0010_alter_post_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
