# Generated by Django 5.0.3 on 2024-04-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0013_cart_cartitem_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
