# Generated by Django 5.0.3 on 2024-04-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0016_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stripe_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
