# Generated by Django 5.0.3 on 2024-04-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0019_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-box', max_length=20),
            preserve_default=False,
        ),
    ]
