# Generated by Django 5.0.3 on 2024-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
