# Generated by Django 5.0.3 on 2024-04-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_stay_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
