# Generated by Django 5.0.3 on 2024-05-03 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('listings', '0007_alter_listing_type'),
        ('reservations', '0003_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_received_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_notifications', to='listings.comment')),
                ('notificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestToBookNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_book_received_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_book_notifications', to='reservations.stay')),
                ('notificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_book_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
