# Generated by Django 5.0.3 on 2024-10-01 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_location_alter_user_profile_pic'),
        ('listings', '0010_remove_listing_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_request_sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_accepted_request_notifications', to='listings.comment')),
                ('notificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_request_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclinedRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_request_sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_declined_request_notifications', to='listings.comment')),
                ('notificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_request_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
