# Generated by Django 5.0.3 on 2024-10-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_acceptedrequestnotification_and_more'),
        ('listings', '0010_remove_listing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedrequestnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_accepted_request_notifications', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='declinedrequestnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_declined_request_notifications', to='listings.listing'),
        ),
    ]
